framework: "isaacgym"
rows: 4
cols: 4
decimation: 4
num_observations: 57
observations: ["ang_vel", "gravity_vec", "commands", "dof_pos", "dof_vel", "actions"]
observations_history: [11,10,9,8,7,6,5,4,3,2,1,0]
clip_obs: 100.0
clip_actions_lower: [-100, -100, -100, -100,
                     -100, -100, -100, -100,
                     -100, -100, -100, -100,
                     -100, -100, -100, -100]
clip_actions_upper: [100, 100, 100, 100,
                     100, 100, 100, 100,
                     100, 100, 100, 100,
                     100, 100, 100, 100]

model_name: "May22_0943.pt" #him kp35 obs12

rl_kp: [35.,35.,35., 0,
        35.,35.,35., 0,
        35.,35.,35., 0,
        35.,35.,35., 0,]
rl_kd: [2, 2, 2, 3,
        2, 2, 2, 3,
        2, 2, 2, 3,
        2, 2, 2, 3,]
torque_limits: [33.25, 33.25, 33.25, 20,
                33.25, 33.25, 33.25, 20,
                33.25, 33.25, 33.25, 20,
                33.25, 33.25, 33.25, 20]
default_dof_pos: [
                  0.0,0.8,-0.65,0.0,
                  0.0,-0.8,0.65,0.0,
                  0.0,0.85,-0.65,0.0,
                  0.0,-0.85,0.65,0.0,
                  ]

hip_scale_reduction: 1
hip_scale_reduction_indices: [0, 4, 8, 12]
num_of_dofs: 16
action_scale: 0.25
lin_vel_scale: 2.0
ang_vel_scale: 0.25
dof_pos_scale: 1.0
dof_vel_scale: 0.05
commands_scale: [2, 2, 0.25]
 
#ISSACGYM
# 'FL_hip_joint', 'FL_thigh_joint', 'FL_calf_joint', 'FL_ankle_joint', 
# 'FR_hip_joint', 'FR_thigh_joint', 'FR_calf_joint', 'FR_ankle_joint', 
# 'RL_hip_joint', 'RL_thigh_joint', 'RL_calf_joint', 'RL_ankle_joint', 
# 'RR_hip_joint', 'RR_thigh_joint', 'RR_calf_joint', 'RR_ankle_joint']

